name: drupal-decoupled-workshop
recipe: drupal9
config:
  xdebug: true
  via: nginx
  webroot: web
  php: '7.4'
  composer_version: '2'
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://drupal-decoupled-workshop.lndo.site"
    build:
      - composer install
tooling:
  drush:
    cmd: /app/vendor/bin/drush
